FORMAT: 1A
HOST: https://193.67.163.23/api/secure

# britishgas

## Group Accounts
Accounts API allows you to list / view all the accounts of the logged in customer. This includes energy accounts, services accounts, multi premise landlord accounts and sales orders of OAM registered and wafer thin profile customers. Responses from this API will be retuned in JSON format only.

## Accounts Collection [/accounts]
### Retrieve a specific Account [GET /accounts/{accountNumber}]
+ Parameters

    + accountNumber (number) ...This is the customers account number
        
+ Request

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "account": {
                    "id": "850034235409",
                    "multiPremiseLandlord": false,
                    "status": "Open",
                    "subType": "Electricity",
                    "responsibilityType": "Legal Payer",
                    "supplyAddress": {
                        "MPRN": null,
                        "postalTown": "Salford",
                        "houseName": "",
                        "address": "53b, Garstang Road North, Salford, Lancashire, WS3 3ER",
                        "county": "LANCASHIRE",
                        "MPAN": null,
                        "houseNumber": "53B",
                        "postcode": "WS3 3ER",
                        "addressLine2": "",
                        "addressLine1": "GARSTANG ROAD NORTH",
                        "flatNumber": null
                    },
                    "type": "Energy",
                    "holderName": "Mr Morita"
                }
            },
            "errors": [],
            "meta": {}
        }

+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": {
                "authorize": "access_denied"
            },
            "meta": {}
        }

+ Response 404 (application/json)

        {
            "status": "ERROR",
            "data": {},
            "errors": {
                "accountNumber": "error.client.account.notfound"
            },
            "meta": {}
        }

### Retrieve all Accounts [GET /accounts]
+ Request

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "accounts": [
                    {
                        "id": "850034235409",
                        "multiPremiseLandlord": false,
                        "status": "Open",
                        "subType": "Electricity",
                        "responsibilityType": "Legal Payer",
                        "supplyAddress": {
                            "MPRN": null,
                            "postalTown": "Salford",
                            "houseName": "",
                            "address": "53b, Garstang Road North, Salford, Lancashire, WS3 3ER",
                            "county": "LANCASHIRE",
                            "MPAN": null,
                            "houseNumber": "53B",
                            "postcode": "WS3 3ER",
                            "addressLine2": "",
                            "addressLine1": "GARSTANG ROAD NORTH",
                            "flatNumber": null
                        },
                        "type": "Energy",
                        "holderName": "Mr Morita"
                    },
                    {
                        "id": "850034336151",
                        "multiPremiseLandlord": false,
                        "status": "Open",
                        "subType": "Gas",
                        "responsibilityType": "Legal Payer",
                        "supplyAddress": {
                            "MPRN": null,
                            "postalTown": "Salford",
                            "houseName": "",
                            "address": "53b, Garstang Road North, Salford, Lancashire, WS3 3ER",
                            "county": "LANCASHIRE",
                            "MPAN": null,
                            "houseNumber": "53B",
                            "postcode": "WS3 3ER",
                            "addressLine2": "",
                            "addressLine1": "GARSTANG ROAD NORTH",
                            "flatNumber": null
                        },
                        "type": "Energy",
                        "holderName": "Mr Morita"
                    }
                ]
            },
            "errors": [],
            "meta": {}
        }

+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": {
                "authorize": "access_denied"
            },
            "meta": {}
        }

## Group Addresses
Addresses API allows you to list / view addresses for a given postcode using `QAS`. Responses from this API will be retuned in JSON format only.

## Addresses Collection [/addresses]
### Retrieve all addresses [GET /addresses{?postcode,house_no}]
+ Parameters

    + postcode (string) ...A valid UK postcode
    + house_no (string, optional) ...House number to restrict the search for

+ Request (application/json)
    
    + Headers
        
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "addresses": [
                    {
                        "MPRN": null,
                        "postalTown": "STAINES-UPON-THAMES",
                        "houseName": "Linden Place",
                        "address": "Flat 10, Linden Place, Fairfield Avenue, STAINES-UPON-THAMES, Middlesex, TW18 4AF, United Kingdom",
                        "county": "Middlesex",
                        "MPAN": "2000003714247",
                        "houseNumber": null,
                        "postcode": "TW18 4AF",
                        "addressLine2": null,
                        "addressLine1": "Fairfield Avenue",
                        "flatNumber": "Flat 10"
                    }
                ]
            },
            "errors": {},
            "meta": {}
        }

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": {
                "postcode": "error.client.postcode.invalid"
            },
            "meta": {}
        }

### Annonymous Supply Check  [GET /addresses/supply-check{?flatNumber,houseNumber,houseName,addressLine1,addressLine2,postalTown,county,postCode}]
+ Parameters

    + flatNumber (string, optional) ...flat number of the selected address, if available.
    + houseNumber (string, optional) ...house number of the selected address, if available.
    + houseName (string, optional) ...house name of the selected address, if available. Atleast one of flat number, house number and house name need to be available for identifying a premise
    + addressLine1 (string, optional) ...street of the selected address, if available.
    + addressLine2 (string, optional) ...locality of the selected address, if available.
    + postalTown (string) ...town or city of the selected address, if available.
    + county (string, optional) ...county of the selected address, if available.
    + postCode (string, optional) ...post code of the selected address, if available.

+ Request (application/json)
    
    + Headers

            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526


+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {},
            "errors": [],
            "meta": {}
        }

+ Response 404 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "checkavailability",
                    "message": "error.client.checkavailability.no.supply"
                }
            ],
            "meta": {}
        }

+ Response 400 (application/json)

        {
            "status": "ERROR",
            "data": {},
            "errors": {
                "postalTown": "error.client.postalTown.blank"
            },
            "meta": {}
        }

+ Response 500 (application/json)

        {
            "status": "ERROR",
            "data": {},
            "errors": {
                "checkavailability": "error.client.checkavailability.no.response"
            },
            "meta": {}
        }

# Logged In supply Check [GET /address/supply-check?houseNumber=1&postCode=SL11AB]

+ Request (application/json)
    
    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "supplyEnergyProducts": true,
                "supplyElectricityProduct": true,
                "supplyServiceProducts": true,
                "supplyGasProduct": true
            },
            "errors": {},
            "meta": {}
        }

## Group Customers
Customers API allows you to list details of current customer represented at Online. Responses from this API will be returned in JSON format only. In order to retrieve information about current customer, client should have logged into to online and supply the access token along with the request.

Customer as a resource identifies current logged in user.

+ id - string
+ title - string
+ firstName - string
+ surname - string
+ dateOfBirth - string
+ primaryTelephoneNumber - Telephone number
+ telephoneNumbers - Array of Telephone numbers
+ correspondeceAddress - Address

Telephone Number
+ number - string
+ type - string

## Customers Collection [/customers]

### Retrieve customers [GET]
+ Request

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "customers": [
                    {
                        "id": "OVh4NnpZUEdNNUxwZTBWRDI5czIxZz09",
                        "title": "Mr",
                        "firstName": "Pentwazz Stavea",
                        "surname": "Kenj",
                        "dateOfBirth": "17/04/1975",
                        "primaryTelephoneNumber": null,
                        "telephoneNumbers": [],
                        "correspondenceAddress": {
                            "address": "67, Beresford Avenue, Surbiton, Surrey, KT5 9LH",
                            "houseNumber": "67",
                            "flatNumber": null,
                            "houseName": null,
                            "addressLine1": "Beresford Avenue",
                            "addressLine2": null,
                            "postalTown": "Surbiton",
                            "county": "SURREY",
                            "postcode": "KT5 9LH",
                            "MPAN": null,
                            "MPRN": null
                        }
                    }
                ]
            },
            "errors": [],
            "meta": {}
        }

+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "authorize",
                    "message": "access_denied"
                }
            ],
            "meta": {}
        }

## Customers Collection [/customers/match-by-account-info]
This is a controller service which allows to find out whether a customer with matching account number, home care number or sales order number, is available in backend system. The request body of this post must be a JSON object with properties listed below.

+ title
+ firstName
+ surname
+ email
+ postcode
+ customerReference

### Customer match by account info [POST]

+ Request (application/json)

    + Headers
    
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
    
            {
                "title": "Mr",
                "firstName": "Pentwazz Stavea",
                "surname": "Kenj",
                "customerReference": "851001347680",
                "email": "Haneesa.Abdulhakkim@bgdigitaltest.co.uk"
            }
        

+ Response 200 (application/json)

            {
                  "status": "SUCCESS",
                  "data": {
                    "customerMatch": {
                      "matchToken": "6e16063a-8a89-5d1a-b9cb-72d14c4c7579",
                      "status": "0xRM91"
                    }
                  },
                  "errors": [],
                  "meta": {}
            }
        
+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "surname",
                    "message": "error.client.surname.blank"
                }
            ],
            "meta": {}
        }


## Customers Match by bank info [/customers/match-by-bank-info]

This is a controller service which allows to find out whether a customer with matching postcode and direct debit bank account number, is available in backend system. The request body of this post must be a JSON object identified with customer. The parameters of the JSON is as follows:

+ title - string
+ firstName - string
+ surname - string
+ email - string
+ postcode - string
+ directDebitNumber - string

### Match by bank info [POST]

+ Request (application/json)
    
    + Headers
        
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
    
            {
                "title": "Mr",
                "firstName": "Pentwazz Stavea",
                "surname": "Kenj",
                "postcode": "TW18 4ND",
                "email": "Haneesa.Abdulhakkim@bgdigitaltest.co.uk",
                "directDebitNumber": "1234"
            }
            
+ Response 200 (application/json)

            {
                  "status": "SUCCESS",
                  "data": {
                    "customerMatch": {
                      "matchToken": null,
                      "status": "0xTXE0"
                    }
                  },
                  "errors": [],
                  "meta": {}
            }
        
+ Response 400 (application/json)

            {
                "status": "FAIL",
                "data": {},
                "errors": [
                    {
                        "code": "surname",
                        "message": "error.client.surname.blank"
                    }
                ],
                "meta": {}
            }
            
+ Response 404 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "error.email.exists",
                    "message": "Customer profile registered with given email address."
                }
            ],
            "meta": {}
        }
        
## Customers Match by postcode [/customers/match-by-postcode]

This is a controller service which allows to find out whether a customer with matching postcode and email address, is available in backend system. The request body of this post must be a JSON object identified with customer. The parameters of the JSON is as follows:

+ title - string
+ firstName - string
+ surname - string
+ email - string
+ postcode - string


### Match by bank info [POST]

+ Request (application/json)
    
    + Headers
        
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
    
            {
                "title": "Mr",
                "firstName": "Pentwazz Stavea",
                "surname": "Kenj",
                "postcode": "TW18 4ND",
                "email": "Haneesa.Abdulhakkim@bgdigitaltest.co.uk"
            }
                    
+ Response 200 (application/json)

            {
                  "status": "SUCCESS",
                  "data": {
                    "customerMatch": {
                      "matchToken": null,
                      "status": "0xTXE0"
                    }
                  },
                  "errors": [],
                  "meta": {}
            }
        
+ Response 400 (application/json)

            {
                "status": "FAIL",
                "data": {},
                "errors": [
                    {
                        "code": "surname",
                        "message": "error.client.surname.blank"
                    }
                ],
                "meta": {}
            }
            
## Customers Account check [/customers/account-check]

This is a controller service allows you to identify what type of accounts customer holds based on the match done previously. As a controller it expects the input in the form of JSON object with an attribute matchToken. Request / response are as follows.

### Account check [POST]

+ Request (application/json)
    
    + Headers
        
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
    
            {
                "matchToken": "0f35b369-ee56-52d8-911d-16fc6d73e70b"
            }
                    
+ Response 200 (application/json)

            {
                  "status": "SUCCESS",
                  "data": {
                    "accountCheck": {
                      "energyAccountsAvailable": true,
                      "serviceAccountsAvailable": true
                    }
                  },
                  "errors": [],
                  "meta": {}
            }
        
+ Response 403 (application/json)

            {
                "status": "FAIL",
                "data": {},
                "errors": [
                    {
                        "code": "matchToken",
                        "message": "error.client.matchToken.invalid"
                    }
                ],
                "meta": {}
            }


## Group UserInfo

Resources related to UserInfo

## UserInfo [/userinfo]
UserInfo resource represents the online profile details of the customer. A UserInfo object has the following attributes:

+ id - represents email address
+ title
+ firstName
+ surname
+ registeredOn
+ type - thin or oam
+ status
+ brand - BG or Sainsburys

### Retrieve logged in UserInfo details [GET]
+ Request (application/json)

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

            {
            "status": "SUCCESS",
            "data": {
                "userinfo": [
                    {
                        "id": "junaid.hussain@centrica.com",
                        "title": "Mr",
                        "firstName": "Junaid",
                        "surname": "Hussain",
                        "registeredOn": "25/05/2015",
                        "type": "FULL",
                        "status": "ACTIVE",
                        "brand": "BG"
                        
                    }
                ]
            },
            "errors": {},
            "meta": {}
        }    

+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "authorize",
                    "message": "access_denied"
                }
            ],
            "meta": {}
        }


        
### Create a new online profile [POST]
+ Request (application/json)

    + Headers
        
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
    
            {
                "userinfo":{
                        "title": "Mr",
                        "firstName": "Junaid",
                        "surname": "Hussain",
                        "brand": "britishgas",
                        "id": "hussainjunaid@hotmail.com"
                    },
                "meta":{
                    "password": "password123",
                    "matchToken": "8c099369-ae94-53ef-a34b-bc8e01dce302"
                }
            }
        
+ Response 200 (application/json)
 
        {
            "status": "SUCCESS",
            "data": {
                "userinfo": [
                    {
                        "id": "junaid.hussain@centrica.com",
                        "title": "Mr",
                        "firstName": "Junaid",
                        "surname": "Hussain",
                        "type": "FULL",
                        "status": "ACTIVE",
                        "brand": "BG"
                    }
                ]
            },
            "errors": [],
            "meta": {}
        }

+ Response 403 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "userinfo",
                    "message": "error.server.userinfo.exists"
                }
            ],
            "meta": {}
        }

+ Response 403 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "userinfo",
                    "message": "error.client.matchToken.invalid"
                }
            ],
            "meta": {}
        }        

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "userinfo",
                    "message": "error.client.firstName.exists"
                }
            ],
            "meta": {}
        } 
        
+ Request (application/json)

    + Headers
        
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f61234

    + Body
    
            {
                "userinfo":{
                        "title": "Mr",
                        "firstName": "J",
                        "surname": "H",
                        "brand": "britishgas",
                        "id": "hussainjunaid@hotmail.com"
                    },
                "meta":{
                    "password": "password123",
                    "onlineSales": "8c099369-ae94-53ef-a34b-bc8e01dce302"
                }
            }
        
+ Response 200 (application/json)
 
        {
            "status": "SUCCESS",
            "data": {
                "userinfo": [
                    {
                        "id": "junaid.hussain@centrica.com",
                        "title": "Mr",
                        "firstName": "J",
                        "surname": "H",
                        "type": "FULL",
                        "status": "ACTIVE",
                        "brand": "BG"
                    }
                ]
            },
            "errors": [],
            "meta": {}
        }

+ Response 403 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "userinfo",
                    "message": "error.server.userinfo.exists"
                }
            ],
            "meta": {}
        } 
        
+ Response 404 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "onlineSales",
                    "message": "error.client.onlineSales.notFound"
                }
            ],
            "meta": {}
        } 

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "firstName",
                    "message": "error.client.firstName.exists"
                }
            ],
            "meta": {}
        } 
        
## UserInfo profile check [/userinfo/profile-check]
This endpoint allows you to check if a given user profile is registered at online or not. 
The request body of this post must be a JSON object with attributes as listed below.

### Profile check [POST]
+ Request (application/json)
    
    + Headers
    
            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
                
            {
                "email" : "Gnanasakthivel.Ramanathan@britishgas.co.uk",
                "brand" : "britishgas"
            
            }

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "profileCheck": {
                    "status": "0xRM91"
                }
            },
            "errors": [],
            "meta": {}
        }
        
+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "email",
                    "message": "error.client.emailAddress.blank"
                }
            ],
            "meta": {}
        } 

## UserInfo by reference [/userinfo/find-by-reference]
This is a controller service which allows to find out whether a user with matching account number, home care number or sales order number, is available in SAP system. The request body of this post must be a JSON object with properties listed below

+ title - Mandatory
+ firstName - Mandatory
+ surname - Mandatory
+ customerReference - Mandatory

### Retrieve userinfo by reference [POST]
+ Request (application/json)
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
                
            {
                "title": "Mr",
                "firstName": "Pentwazz Stavea",
                "surname": "Kenj",
                "customerReference": "851001347680
            
            }

+ Response 200 (application/json)
            
            {
                "status": "SUCCESS",
                "data": {
                    "email": "gnanasakthivel.ramanathan@britishgas.co.uk"
                },
                "errors": [],
                "meta": {}
            }

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "title",
                    "message": "error.client.title.blank"
                }
            ],
            "meta": {}
        } 

+ Response 403 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "userinfo",
                    "message": "error.server.userinfo.invalid"
                }
            ],
            "meta": {}
        } 
        
+ Response 403 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "userinfo",
                    "message": "error.server.userinfo.notFound"
                }
            ],
            "meta": {}
        }
        
## Temporary profiles [/userinfo/temporary-profiles]
Creates a profile and triggers an email using a temporary password.
As an entity, following properties define a Temporary profile.

+ id - Optional
+ title - Mandatory
+ firstName - Mandatory
+ surname - Mandatory
+ email - Mandatory

### Create temporary profile [POST]
+ Request (application/json)
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
                
            {
                "temporaryProfile": {
                    "title": "Mr",
                    "firstName": "M",
                    "surname": "Street",
                    "email": "emailAddress@bgdigitaltest.co.uk"
                },
                "meta": {
                    "matchToken": "750319c2-dee6-5113-95f9-a1b501124a64"
                }
            }

+ Response 200 (application/json)

        {
              "status": "SUCCESS",
              "data": {
                "temporaryProfile": {
                  "id": "5aa6a106-c6d5-52c4-af9d-a3d0b361dffa",
                  "firstName": "M",
                  "surname": "Street",
                  "title": "Mr",
                  "email": "pradeepkrishna.govindaraju@centrica.com"
                }
              },
              "errors": [],
              "meta": {}
        }

+ Response 400 (application/json)

        {
              "status": "FAIL",
              "data": {},
              "errors": [
                {
                  "code": "matchToken",
                  "message": "error.client.matchToken.invalid"
                }
              ],
              "meta": {}
        }
        
+ Response 400 (application/json)

        {
              "status": "FAIL",
              "data": {},
              "errors": [
                {
                  "code": "firstName",
                  "message": "error.client.firstName.blank"
                }
              ],
              "meta": {}
        }
        
### Update temporary profile [PUT]

+ Request (application/json)
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
                
            {
                "temporaryProfile": {
                  "id": "5aa6a106-c6d5-52c4-af9d-a3d0b361dffa",
                  "firstName": "M",
                  "surname": "Street",
                  "title": "Mr",
                  "email": "pradeepkrishna.govindaraju@centrica.com"
                },
                "meta": {
                    "password": "password12"
                }
            }

+ Response 200 (application/json)

        {
                  "status": "SUCCESS",
                  "data": {},
                  "errors": [],
                  "meta": {}
               
        }

+ Response 404 (application/json)

        {
              "status": "FAIL",
              "data": {},
              "errors": [
                {
                  "code": "temporaryProfile",
                  "message": "error.client.temporaryProfile.invalid"
                }
              ],
              "meta": {}
        }
        
+ Response 400 (application/json)

        {
              "status": "FAIL",
              "data": {},
              "errors": [
                {
                  "code": "userinfo",
                  "message": "error.server.userinfo.exists"
                }
              ],
              "meta": {}
        }
        
+ Response 400 (application/json)

        {
              "status": "FAIL",
              "data": {},
              "errors": [
                {
                  "code": "firstName",
                  "message": "error.client.firstName.blank"
                }
              ],
              "meta": {}
        }
        
+ Response 400 (application/json)

        {
              "status": "FAIL",
              "data": {},
              "errors": [
                {
                  "code": "password",
                  "message": "error.client.password.invalid"
                }
              ],
              "meta": {}
        }
        
## Temporary Profile tokeninfo [/userinfo/temporary-profiles/token-info{?token}]

+ Parameters

    + token: 5aa6a106-c6d5-52c4-af9d-a3d0b361dffa (mandatory, string)
    
### Retrieve tokeninfo for password reset [GET]
+ Request
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)
        
        {
              "title": "Mr",
              "email": "pradeepkrishna.govindaraju@centrica.com",
              "expiresIn": 1177,
              "surname": "Street",
              "firstName": "M"
        }

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "token",
                    "message": "error.client.token.invalid"
                }
            ],
            "meta": {}
        }
        
## Reset password request [/userinfo/reset-password-requests]
Reset password request endpoint allows a client to reset the current password for a customer.
As a resource, a ResetPasswordRequest represents following attributes.

+ email
+ brand
+ password
+ token

### Send password reset email [POST]
+ Request (application/json)
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
                
            {
                "resetPasswordRequest": 
                {
                    "email" : "pradeepkrishna.govindarajucentrica.com",
                    "brand" : "britishgas"
                }
            }

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {},
            "errors": [],
            "meta": {}
        }

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "email",
                    "message": "error.client.email.invalid"
                }
            ],
            "meta": {}
        }
        
+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "brand",
                    "message": "error.client.brand.invalid"
                }
            ],
            "meta": {}
        }
        
### Updating a new password [PUT]
Should you have a valid token to used via an email sent across, use this endpoint to update the new password for that customer.

Note: As soon as the password update is successful, token issued will be invalidated. Token can also be marked invalid if it has expired. Current expiry timelimit is 20 minutes.
+ Request (application/json)
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

    + Body
    
            {
                "resetPasswordRequest": 
                {
                    "token" : "f2d779a9-748b-58bc-aacb-8714b1206656",
                    "password" : "password12"
                }
            }

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {},
            "errors": [],
            "meta": {}
        }
        
+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "payload",
                    "message": "error.client.token.invalid"
                }
            ],
            "meta": {}
        }        

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "password",
                    "message": "error.client.password.invalid"
                }
            ],
            "meta": {}
        }
        
## Reset password request tokeninfo [/userinfo/reset-password-requests/token-info{?token}]

+ Parameters

    + token: 5aa6a106-c6d5-52c4-af9d-a3d0b361dffa (mandatory, string)
    
### Retrieve tokeninfo for password reset [GET]
+ Request
    
    + Headers
            
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)
        
        {
              "title": "Mr",
              "email": "pradeepkrishna.govindaraju@centrica.com",
              "expiresIn": 1177,
              "surname": "Street",
              "firstName": "M"
        }

+ Response 400 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "token",
                    "message": "error.client.token.invalid"
                }
            ],
            "meta": {}
        }


## Group Direct Debits
Direct Debits API allows you to list / view all the direct debit information of the logged in customer. Currently it supports only fixed monthly direct debit. Responses from this API will be returned in JSON format only.

## Direct Debits collection [/directdebits]
### Retrieve all direct debits [GET]
+ Request

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526
            
+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "directdebits": [
                    {
                        "id": "851001347400",
                        "account": "851001347400",
                        "numberOfInstallments": 10,
                        "numberOfPendingInstallments": 10,
                        "installments": [
                            {
                                "date": "26/05/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/06/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/07/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/08/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/09/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/10/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/11/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/12/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/01/2016",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/02/2016",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            }
                        ]
                    }
                ]
            },
            "errors": [],
            "meta": {}
        }
        
+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "authorize",
                    "message": "access_denied"
                }
            ],
            "meta": {}
        }

### Retrieve all direct debits for accounts [GET /directdebits{?accountNumber}]
+ Parameters

    + accountNumber (optional, string) ...Multiple account numbers each one a seperate accountNumber= definition

+ Request

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526
            
+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "directdebits": [
                    {
                        "id": "851001347400",
                        "account": "851001347400",
                        "numberOfInstallments": 10,
                        "numberOfPendingInstallments": 10,
                        "installments": [
                            {
                                "date": "26/05/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/06/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/07/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/08/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/09/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/10/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/11/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/12/2015",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/01/2016",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            },
                            {
                                "date": "25/02/2016",
                                "status": "pending",
                                "gasAmount": 17,
                                "electricityAmount": 15,
                                "totalAmount": 32
                            }
                        ]
                    }
                ]
            },
            "errors": [],
            "meta": {}
        }
        
+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "authorize",
                    "message": "access_denied"
                }
            ],
            "meta": {}
        }
        

### Get a specific Direct Debit [GET /directdebits/{directDebitId}]

+ Parameters

    + directDebitId (string) ...directDebitId is the account number associated to the contract
    
+ Request

    + Headers

            Authorization: Bearer accesstoken
            cid: 05e230bf-a9cf-4b31-bc54-d3a995f62526

+ Response 200 (application/json)

        {
            "status": "SUCCESS",
            "data": {
                "directdebit": {
                    "id": "851001347400",
                    "account": "851001347400",
                    "numberOfInstallments": 10,
                    "numberOfPendingInstallments": 10,
                    "installments": [
                        {
                            "date": "26/05/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/06/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/07/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/08/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/09/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/10/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/11/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/12/2015",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/01/2016",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        },
                        {
                            "date": "25/02/2016",
                            "status": "pending",
                            "gasAmount": 17,
                            "electricityAmount": 15,
                            "totalAmount": 32
                        }
                    ]
                }
            },
            "errors": [],
            "meta": {}
        }
        
+ Response 401 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "authorize",
                    "message": "access_denied"
                }
            ],
            "meta": {}
        }

+ Response 404 (application/json)

        {
            "status": "FAIL",
            "data": {},
            "errors": [
                {
                    "code": "directdebit",
                    "message": "error.client.directdebit.notfound"
                }
            ],
            "meta": {}
        }